name: Test code on Python 3.11.2
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: list repo
        run: |
          ls
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - name: setup venv
        run: |
          make setup
      - name: activate venv
        run: |
          make source
      - name: install dependencies
        run: |
          make install
      - name: lint check
        run: |
          make lint-check
      - name: run tests
        run: |
          make test
      - name: clean up dir
        run: |
          make clean
